### ISSUE TITLE
Broken when working with compact HTML

### ISSUE THREAD

**Issue by buckle2000** [KingPixil/moon-router#10]
This bug took me 1 hour.

This will work:
https://jsfiddle.net/2h4mj2xt/1/

This will break:
https://jsfiddle.net/2h4mj2xt/3/

Seems like if there is no whitespace before/after `<router-view>` tag, the router won't work.

Anyway, moon.js is a great library.

**Comment by kbrsh** [comment]
Sorry! This happens because the whitespace between the `<router-view>` tags tell Moon that it might have slots, so the compiler deoptimizes it. On the other hand, when you just have a `<router-view>`, Moon sees no dynamic aspects of it and the compiler will optimize it. This means that the `<router-view>` will never be updated.

This has already been fixed in v1.
